---
- name: updating os
  include_vars: "vars/main.yml"
  tags: always

- name: updating os
  include_tasks: "tasks/update.yml"
  tags: always

- name: Include req
  include_tasks: "tasks/install.yml"
  tags: always